# Generated by Django 3.0.3 on 2020-05-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('breed', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Walkie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_measurement', models.CharField(max_length=2)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_info.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treat_type', models.CharField(max_length=25)),
                ('amount_measurement', models.CharField(max_length=15)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_info.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_info.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_measurement', models.CharField(max_length=15)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_info.Dog')),
            ],
        ),
    ]
