# Generated by Django 3.0.3 on 2020-05-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='amount_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='out',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treat',
            name='amount_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treat',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkie',
            name='distance_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkie',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
